package me.thinksmp.commands.normalCommands;

import me.thinksmp.utility.GeneralUtility;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandMap;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.inventory.InventoryCloseEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.InventoryHolder;
import org.bukkit.inventory.ItemFlag;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.jetbrains.annotations.NotNull;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.IdentityHashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


// this was generated by Chat GPT 5.5 Extended thinking model
// this is why every function is in here, all at once, i will later refactor it my self and organize it when i can.
public final class CommandsGUI implements CommandExecutor, Listener {

    private static final String TITLE = GeneralUtility.translate("&8Available Commands");
    private static final int SIZE = 54;
    private static final int COMMANDS_PER_PAGE = 28;

    private static final int PREVIOUS_SLOT = 45;
    private static final int NEXT_SLOT = 53;

    private static final int[] COMMAND_SLOTS = {
            10, 11, 12, 13, 14, 15, 16,
            19, 20, 21, 22, 23, 24, 25,
            28, 29, 30, 31, 32, 33, 34,
            37, 38, 39, 40, 41, 42, 43
    };

    @Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, String[] args) {
        if (!(sender instanceof Player player)) {
            return true;
        }

        open(player, 0);
        return true;
    }

    private void open(Player player, int page) {
        List<CommandInfo> commands = getAllowedCommands(player);

        int maxPage = Math.max(0, (int) Math.ceil(commands.size() / (double) COMMANDS_PER_PAGE) - 1);
        page = Math.max(0, Math.min(page, maxPage));

        Inventory inventory = Bukkit.createInventory(new CommandsHolder(page), SIZE, TITLE);

        ItemStack glass = item(getMaterial("GRAY_STAINED_GLASS_PANE", "STAINED_GLASS_PANE"), "&7", Collections.emptyList());

        for (int i = 0; i < SIZE; i++) {
            inventory.setItem(i, glass);
        }

        int start = page * COMMANDS_PER_PAGE;
        int end = Math.min(commands.size(), start + COMMANDS_PER_PAGE);

        int slotIndex = 0;

        for (int i = start; i < end; i++) {
            CommandInfo info = commands.get(i);
            inventory.setItem(COMMAND_SLOTS[slotIndex++], createCommandItem(info));
        }

        if (page > 0) {
            inventory.setItem(PREVIOUS_SLOT, item(
                    Material.ARROW,
                    "&ePrevious Page",
                    List.of("&7Click to go to page &e" + page)
            ));
        }

        if (page < maxPage) {
            inventory.setItem(NEXT_SLOT, item(
                    Material.ARROW,
                    "&eNext Page",
                    List.of("&7Click to go to page &e" + (page + 2))
            ));
        }

        inventory.setItem(49, item(
                Material.BOOK,
                "&aCommands",
                List.of(
                        "&7Page: &e" + (page + 1) + "&7/&e" + (maxPage + 1),
                        "&7Commands: &e" + commands.size()
                )
        ));

        player.openInventory(inventory);
    }

    @EventHandler
    public void onInventoryClick(InventoryClickEvent event) {
        if (!(event.getInventory().getHolder() instanceof CommandsHolder holder)) {
            return;
        }

        event.setCancelled(true);

        if (!(event.getWhoClicked() instanceof Player player)) {
            return;
        }

        int slot = event.getRawSlot();

        if (slot == PREVIOUS_SLOT) {
            open(player, holder.page - 1);
            return;
        }

        if (slot == NEXT_SLOT) {
            open(player, holder.page + 1);
        }
    }

    @EventHandler
    public void onInventoryClose(InventoryCloseEvent event) {
        if (!(event.getInventory().getHolder() instanceof CommandsHolder)) {
            return;
        }
    }

    private List<CommandInfo> getAllowedCommands(Player player) {
        Map<String, Command> knownCommands = getKnownCommands();
        Set<Command> seen = Collections.newSetFromMap(new IdentityHashMap<>());
        List<CommandInfo> result = new ArrayList<>();

        for (Map.Entry<String, Command> entry : knownCommands.entrySet()) {
            Command command = entry.getValue();

            if (command == null || seen.contains(command)) {
                continue;
            }

            seen.add(command);

            if (!canUse(player, command)) {
                continue;
            }

            String name = command.getName();

            if (name == null || name.trim().isEmpty()) {
                name = entry.getKey();
            }

            result.add(new CommandInfo(
                    name,
                    command.getDescription(),
                    command.getUsage(),
                    command.getAliases(),
                    command.getPermission()
            ));
        }

        result.sort(Comparator.comparing(info -> info.name.toLowerCase()));
        return result;
    }

    private boolean canUse(Player player, Command command) {
        try {
            return command.testPermissionSilent(player);
        } catch (Throwable ignored) {
            String permission = command.getPermission();

            if (permission == null || permission.trim().isEmpty()) {
                return true;
            }

            return player.hasPermission(permission);
        }
    }

    private Map<String, Command> getKnownCommands() {
        try {
            CommandMap commandMap = getCommandMap();

            if (commandMap == null) {
                return Collections.emptyMap();
            }

            Field knownCommandsField = commandMap.getClass().getDeclaredField("knownCommands");
            knownCommandsField.setAccessible(true);

            Object value = knownCommandsField.get(commandMap);

            if (!(value instanceof Map<?, ?> map)) {
                return Collections.emptyMap();
            }

            Map<String, Command> commands = new LinkedHashMap<>();

            for (Map.Entry<?, ?> entry : map.entrySet()) {
                if (entry.getKey() instanceof String key && entry.getValue() instanceof Command command) {
                    commands.put(key, command);
                }
            }

            return commands;
        } catch (Throwable ignored) {
            return Collections.emptyMap();
        }
    }

    private CommandMap getCommandMap() {
        try {
            Method method = Bukkit.getServer().getClass().getMethod("getCommandMap");
            Object value = method.invoke(Bukkit.getServer());

            if (value instanceof CommandMap commandMap) {
                return commandMap;
            }
        } catch (Throwable ignored) {
        }

        try {
            Field field = Bukkit.getServer().getClass().getDeclaredField("commandMap");
            field.setAccessible(true);
            Object value = field.get(Bukkit.getServer());

            if (value instanceof CommandMap commandMap) {
                return commandMap;
            }
        } catch (Throwable ignored) {
        }

        return null;
    }

    private ItemStack createCommandItem(CommandInfo info) {
        List<String> lore = new ArrayList<>();

        if (info.description != null && !info.description.trim().isEmpty()) {
            lore.add("&7Description:");
            lore.add("&f" + info.description);
            lore.add("");
        }

        if (info.usage != null && !info.usage.trim().isEmpty()) {
            lore.add("&7Usage:");
            lore.add("&e" + cleanUsage(info.usage));
            lore.add("");
        }

        if (info.aliases != null && !info.aliases.isEmpty()) {
            lore.add("&7Aliases:");
            lore.add("&e" + String.join("&7, &e", info.aliases));
            lore.add("");
        }

        if (info.permission != null && !info.permission.trim().isEmpty()) {
            lore.add("&7Permission:");
            lore.add("&e" + info.permission);
        } else {
            lore.add("&7Permission:");
            lore.add("&aNone");
        }

        return item(getMaterial("WRITABLE_BOOK", "BOOK_AND_QUILL"), "&a/" + info.name, lore);
    }

    private String cleanUsage(String usage) {
        if (usage == null) {
            return "";
        }

        return usage.replace("<command>", "").replace("/", "").trim().isEmpty()
                ? "/" + usage
                : usage;
    }

    private ItemStack item(Material material, String name, List<String> lore) {
        ItemStack item = new ItemStack(material == null ? Material.BOOK : material, 1);
        ItemMeta meta = item.getItemMeta();

        if (meta != null) {
            meta.setDisplayName(GeneralUtility.translate(name));

            if (lore != null && !lore.isEmpty()) {
                List<String> translated = new ArrayList<>();

                for (String line : lore) {
                    translated.add(GeneralUtility.translate(line));
                }

                meta.setLore(translated);
            }

            try {
                meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
            } catch (Throwable ignored) {
            }

            item.setItemMeta(meta);
        }

        return item;
    }

    private Material getMaterial(String modern, String legacy) {
        Material material = Material.matchMaterial(modern);

        if (material != null) {
            return material;
        }

        material = Material.matchMaterial(legacy);

        if (material != null) {
            return material;
        }

        return Material.BOOK;
    }

    private static final class CommandsHolder implements InventoryHolder {
        private final int page;

        private CommandsHolder(int page) {
            this.page = page;
        }

        @Override
        public Inventory getInventory() {
            return null;
        }
    }

    private static final class CommandInfo {
        private final String name;
        private final String description;
        private final String usage;
        private final List<String> aliases;
        private final String permission;

        private CommandInfo(String name, String description, String usage, List<String> aliases, String permission) {
            this.name = name;
            this.description = description == null ? "" : description;
            this.usage = usage == null ? "" : usage;
            this.aliases = aliases == null ? Collections.emptyList() : aliases;
            this.permission = permission;
        }
    }
}
